### ISSUE TITLE
Doesn't appear to be running at all

### ISSUE THREAD

**Issue by GregSutcliffe** [mjanser/firefox-addon-owncloud-bookmarks#6]
Client: Archlinux x86_64
Browser: Firefox 47.0.1
Server: NextCloud 9.0.52 / Bookmarks 0.7

Firefox shows the addon as enabled, and has my login stored in the password store (confirmed by logout/login on the Nextcloud server). App configured with correct URL, server is SSL with valid LetsEncrypt cert (so nothing self-signed). The bookmarks API is working (confirmed via `curl -q -O - https://domain.tld/index.php/apps/bookmarks/public/rest/v1/bookmark?user=admin&password=test1234`)

However, the configured folder is never created in Firefox, and I can't see any hits in the server logs when I click "Synchronize now" in the addon preferences. Is there any more debugging I can do?

**Comment by mjanser** [comment]
Hm, can you have a look in the "Browser Console" of Firefox (developer tools) when you click on the sync button? The add-on should log errors there.

**Comment by GregSutcliffe** [comment]
Aha, that was more productive:

```
A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Mon Jul 18 2016 14:52:43 GMT+0100 (BST)
Full Message: RequirementError: The `title` property must be defined.
Full Stack: JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: PendingErrors.register :: line 195
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.completePromise :: line 718
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: Handler.prototype.process :: line 973
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.walkerLoop :: line 816
JS frame :: resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js :: this.PromiseWalker.scheduleWalkerLoop/< :: line 750 (unknown)
```

**Comment by GregSutcliffe** [comment]
@mjanser is the browser console output useful? Would love to get this set up :)

**Comment by sirio81** [comment]
On firefox 45.2.0, debian 8 also doesn't work at all.

**Comment by mjanser** [comment]
Sorry for the late response. This problem looks like you have bookmarks without a title. I published a new version of this add-on to fix this.

**Comment by GregSutcliffe** [comment]
No worries, we all get busy :)

So this doesn't seem to have fixed it. I'm still getting promise chain errors in the browser console. My bookmarks definitely have titles (see screenshot below), but I also don't see anything logged in the server logs either, so it's hard to believe it's actually retrieving the bookmark data in the first place.

For the record, I've upgraded to Nextcloud 10 and Bookmarks 0.9.1 RC1

![2016-08-28-031027_1695x651_scrot](https://cloud.githubusercontent.com/assets/827786/18031196/0fd449ec-6ccd-11e6-957e-c95984b5a124.png)

**Comment by mjanser** [comment]
I deprecated this add-on in favor of https://addons.mozilla.org/de/firefox/addon/floccus.
